/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AndelAmbulanceWlList {
    }
}
declare global {
    interface HTMLAndelAmbulanceWlListElement extends Components.AndelAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLAndelAmbulanceWlListElement: {
        prototype: HTMLAndelAmbulanceWlListElement;
        new (): HTMLAndelAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "andel-ambulance-wl-list": HTMLAndelAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface AndelAmbulanceWlList {
    }
    interface IntrinsicElements {
        "andel-ambulance-wl-list": AndelAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "andel-ambulance-wl-list": LocalJSX.AndelAmbulanceWlList & JSXBase.HTMLAttributes<HTMLAndelAmbulanceWlListElement>;
        }
    }
}
